name: Docker Image CI

on:
  push:
    branches: 
     - main
    tags: 
     - '*'
     
  pull_request:
    branches: 
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
        name: Checkout
        uses: actions/checkout@v2
    
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
    -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/gapidobri/steam-openid-connect-provider
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest
          
    -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src/
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
